version: 2
updates:
- package-ecosystem: "nuget"
  directory: "/Source"
  schedule:
    interval: "5 minutes"  
  target-branch: "master"
  commit-message:
    prefix: "Dependency (dependabot/nuget):"
  labels:
  - ":heavy_check_mark: dependencies"
- package-ecosystem: "npm"
  directory: "/Website"
  schedule:
    interval: "5 minutes"
  target-branch: "master"
  commit-message:
    prefix: "Dependency (dependabot/npm):"
  labels:
  - ":heavy_check_mark: dependencies"
